version: '2'
volumes:
  html:
  mysql:
services:
  web:
    image: crinis/hlxce
    environment:
      DB_HOST: db
      DB_USERNAME: hlxce
      DB_PASSWORD: hlxce
      DB_NAME: hlxce
    links:
    - db:db
    - daemon:daemon
    ports: 
    - 80:80
    #volumes:
    # persist /var/www/html/ if you want to - this means manual upgrading next time
    # - html:/var/www/html/
  daemon:
    image: crinis/hlxce-daemon
    environment:
      DB_HOST: db
      DB_USERNAME: hlxce
      DB_PASSWORD: hlxce
      DB_NAME: hlxce
    links:
    - db:db
    ports: 
    # the perl daemon listens on port 27500 by default
    - 27500:27500/udp
  db:
    image: mariadb:5
    environment:
      MYSQL_USER: hlxce
      MYSQL_PASSWORD: hlxce
      MYSQL_DATABASE: hlxce
      MYSQL_ROOT_PASSWORD: hlxce
    volumes:
    # This is important as it persists your database, if you don't do that all data will be lost when a containers gets destroyed
    - mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: '3306'
    links:
    - db:db
    ports:
    # Change this port if you don't want it running at port 8080
    - 8080:80
    cpu_shares: 128
